spring.application.name=LearningSystem
server.port=8080

spring.datasource.url=jdbc:h2:mem:learningdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true
info.app.name=Microservicio de Cursos CloudNative
info.app.version=1.0.2
info.app.description=API REST para sistema de Cursos